version: 2
updates:
- package-ecosystem: maven
  directory: "/jpasskit"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "4.0"
- package-ecosystem: maven
  directory: "/jpasskit.server"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "4.0"
